name: CI Testing

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.9', '3.10']
        poetry-version: ["1.2.2"]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python {% raw %}${{ matrix.python-version }}{% endraw %}

        uses: actions/setup-python@v4
        with:
          python-version: {% raw %}${{ matrix.python-version }}{% endraw %}

      - name: Install dependencies
        run: |
          python -m pip install -r requirements/base.txt
          python -m pip install -r requirements/dev.txt
          python -m pip install -e .

      - name: Collect coverage
        run: python -m pytest tests --cov={{cookiecutter.package_name}} --cov-report=xml

      - name: Upload coverage to CodeCov
        uses: codecov/codecov-action@v3
        with:
          file: coverage.xml
          token: {% raw %}${{ secrets.CODECOV_TOKEN }}{% endraw %}